### ISSUE TITLE
Space allocation and 0 values

### ISSUE THREAD

**Issue by fuu1** [ChrisAnd1998/Aerial#2]
Right and Bottom Space allocation seem to work incorrectly:
* Any Value will have the space assigned wrong
* 0 Values will allocate space and not reset

OS: Windows 10 - 2004(19041)
Here is a short video showcasing the issue: [Video link](https://streamable.com/esfapm)

**Comment by ChrisAnd1998** [comment]
Fixed ;)

**Comment by th3jesta** [comment]
I was still having this issue, but I found a solution: in the application properties->Compatibility->Change High DPI settings->Override... choose Application.
